# Generated by Django 3.1.5 on 2021-01-27 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_worker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('start_date', models.DateField()),
                ('start_hour', models.IntegerField()),
                ('max_participants', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='worker',
            name='position',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.AddField(
            model_name='worker',
            name='tournament',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='my_app.tournament'),
            preserve_default=False,
        ),
    ]
