# Generated by Django 3.1.5 on 2021-01-27 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_auto_20210127_2049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='max_participants',
            new_name='participants_limit',
        ),
    ]
